-- Create common_stocks table for managing 500 common stocks used in market calculations
-- These stocks are used by the hourly cron job to calculate top gainers, losers, and most active
CREATE TABLE IF NOT EXISTS common_stocks (
  symbol TEXT PRIMARY KEY,
  name TEXT,
  exchange TEXT,
  added_at INTEGER DEFAULT (strftime('%s', 'now')),
  is_active INTEGER DEFAULT 1
);

-- Index on is_active for filtering active stocks efficiently
CREATE INDEX IF NOT EXISTS idx_common_stocks_is_active ON common_stocks(is_active);

-- Insert initial 500 common stocks (major indices and high-volume stocks)
-- This list includes S&P 500 constituents and other major market stocks
INSERT OR IGNORE INTO common_stocks (symbol, name, exchange, is_active) VALUES
('AAPL', 'Apple Inc.', 'NASDAQ', 1),
('MSFT', 'Microsoft Corporation', 'NASDAQ', 1),
('GOOGL', 'Alphabet Inc.', 'NASDAQ', 1),
('AMZN', 'Amazon.com Inc.', 'NASDAQ', 1),
('NVDA', 'NVIDIA Corporation', 'NASDAQ', 1),
('META', 'Meta Platforms Inc.', 'NASDAQ', 1),
('TSLA', 'Tesla Inc.', 'NASDAQ', 1),
('BRK.B', 'Berkshire Hathaway Inc.', 'NYSE', 1),
('V', 'Visa Inc.', 'NYSE', 1),
('JNJ', 'Johnson & Johnson', 'NYSE', 1),
('WMT', 'Walmart Inc.', 'NYSE', 1),
('JPM', 'JPMorgan Chase & Co.', 'NYSE', 1),
('MA', 'Mastercard Incorporated', 'NYSE', 1),
('PG', 'The Procter & Gamble Company', 'NYSE', 1),
('UNH', 'UnitedHealth Group Incorporated', 'NYSE', 1),
('HD', 'The Home Depot Inc.', 'NYSE', 1),
('DIS', 'The Walt Disney Company', 'NYSE', 1),
('BAC', 'Bank of America Corp.', 'NYSE', 1),
('ADBE', 'Adobe Inc.', 'NASDAQ', 1),
('NFLX', 'Netflix Inc.', 'NASDAQ', 1),
('PYPL', 'PayPal Holdings Inc.', 'NASDAQ', 1),
('CMCSA', 'Comcast Corporation', 'NASDAQ', 1),
('XOM', 'Exxon Mobil Corporation', 'NYSE', 1),
('VZ', 'Verizon Communications Inc.', 'NYSE', 1),
('CSCO', 'Cisco Systems Inc.', 'NASDAQ', 1),
('PFE', 'Pfizer Inc.', 'NYSE', 1),
('CVX', 'Chevron Corporation', 'NYSE', 1),
('ABT', 'Abbott Laboratories', 'NYSE', 1),
('KO', 'The Coca-Cola Company', 'NYSE', 1),
('AVGO', 'Broadcom Inc.', 'NASDAQ', 1),
('COST', 'Costco Wholesale Corporation', 'NASDAQ', 1),
('MRK', 'Merck & Co. Inc.', 'NYSE', 1),
('PEP', 'PepsiCo Inc.', 'NASDAQ', 1),
('TMO', 'Thermo Fisher Scientific Inc.', 'NYSE', 1),
('ACN', 'Accenture plc', 'NYSE', 1),
('ABBV', 'AbbVie Inc.', 'NYSE', 1),
('TXN', 'Texas Instruments Incorporated', 'NASDAQ', 1),
('NKE', 'Nike Inc.', 'NYSE', 1),
('MDT', 'Medtronic plc', 'NYSE', 1),
('HON', 'Honeywell International Inc.', 'NASDAQ', 1),
('QCOM', 'QUALCOMM Incorporated', 'NASDAQ', 1),
('PM', 'Philip Morris International Inc.', 'NYSE', 1),
('LIN', 'Linde plc', 'NYSE', 1),
('RTX', 'Raytheon Technologies Corporation', 'NYSE', 1),
('LOW', 'Lowe''s Companies Inc.', 'NYSE', 1),
('AMGN', 'Amgen Inc.', 'NASDAQ', 1),
('BMY', 'Bristol-Myers Squibb Company', 'NYSE', 1),
('UPS', 'United Parcel Service Inc.', 'NYSE', 1),
('DE', 'Deere & Company', 'NYSE', 1),
('SBUX', 'Starbucks Corporation', 'NASDAQ', 1),
('INTU', 'Intuit Inc.', 'NASDAQ', 1),
('CAT', 'Caterpillar Inc.', 'NYSE', 1),
('AMAT', 'Applied Materials Inc.', 'NASDAQ', 1),
('ISRG', 'Intuitive Surgical Inc.', 'NASDAQ', 1),
('ADP', 'Automatic Data Processing Inc.', 'NASDAQ', 1),
('BKNG', 'Booking Holdings Inc.', 'NASDAQ', 1),
('CI', 'Cigna Corporation', 'NYSE', 1),
('GILD', 'Gilead Sciences Inc.', 'NASDAQ', 1),
('ELV', 'Elevance Health Inc.', 'NYSE', 1),
('SCHW', 'The Charles Schwab Corporation', 'NYSE', 1),
('AXP', 'American Express Company', 'NYSE', 1),
('GE', 'General Electric Company', 'NYSE', 1),
('LMT', 'Lockheed Martin Corporation', 'NYSE', 1),
('BLK', 'BlackRock Inc.', 'NYSE', 1),
('C', 'Citigroup Inc.', 'NYSE', 1),
('REGN', 'Regeneron Pharmaceuticals Inc.', 'NASDAQ', 1),
('AMD', 'Advanced Micro Devices Inc.', 'NASDAQ', 1),
('DHR', 'Danaher Corporation', 'NYSE', 1),
('NOW', 'ServiceNow Inc.', 'NYSE', 1),
('ADI', 'Analog Devices Inc.', 'NASDAQ', 1),
('PLD', 'Prologis Inc.', 'NYSE', 1),
('TJX', 'The TJX Companies Inc.', 'NYSE', 1),
('CDNS', 'Cadence Design Systems Inc.', 'NASDAQ', 1),
('SNPS', 'Synopsys Inc.', 'NASDAQ', 1),
('AON', 'Aon plc', 'NYSE', 1),
('ZTS', 'Zoetis Inc.', 'NYSE', 1),
('EQIX', 'Equinix Inc.', 'NASDAQ', 1),
('FI', 'Fiserv Inc.', 'NASDAQ', 1),
('CME', 'CME Group Inc.', 'NASDAQ', 1),
('APH', 'Amphenol Corporation', 'NYSE', 1),
('KLAC', 'KLA Corporation', 'NASDAQ', 1),
('FAST', 'Fastenal Company', 'NASDAQ', 1),
('MCHP', 'Microchip Technology Incorporated', 'NASDAQ', 1),
('PANW', 'Palo Alto Networks Inc.', 'NASDAQ', 1),
('CDW', 'CDW Corporation', 'NASDAQ', 1),
('FTNT', 'Fortinet Inc.', 'NASDAQ', 1),
('PAYX', 'Paychex Inc.', 'NASDAQ', 1),
('TGT', 'Target Corporation', 'NYSE', 1),
('VRTX', 'Vertex Pharmaceuticals Incorporated', 'NASDAQ', 1),
('ALGN', 'Align Technology Inc.', 'NASDAQ', 1),
('IDXX', 'IDEXX Laboratories Inc.', 'NASDAQ', 1),
('DXCM', 'Dexcom Inc.', 'NASDAQ', 1),
('ODFL', 'Old Dominion Freight Line Inc.', 'NASDAQ', 1),
('CHTR', 'Charter Communications Inc.', 'NASDAQ', 1),
('ANSS', 'ANSYS Inc.', 'NASDAQ', 1),
('MELI', 'MercadoLibre Inc.', 'NASDAQ', 1),
('BKR', 'Baker Hughes Company', 'NASDAQ', 1),
('ETN', 'Eaton Corporation plc', 'NYSE', 1),
('CMI', 'Cummins Inc.', 'NYSE', 1),
('APH', 'Amphenol Corporation', 'NYSE', 1),
('FDX', 'FedEx Corporation', 'NYSE', 1),
('PCAR', 'PACCAR Inc', 'NASDAQ', 1),
('NDAQ', 'Nasdaq Inc.', 'NASDAQ', 1),
('MTCH', 'Match Group Inc.', 'NASDAQ', 1),
('ON', 'ON Semiconductor Corporation', 'NASDAQ', 1),
('MPWR', 'Monolithic Power Systems Inc.', 'NASDAQ', 1),
('SWAV', 'Shockwave Medical Inc.', 'NASDAQ', 1),
('ZS', 'Zscaler Inc.', 'NASDAQ', 1),
('DOCN', 'DigitalOcean Holdings Inc.', 'NYSE', 1),
('CRWD', 'CrowdStrike Holdings Inc.', 'NASDAQ', 1),
('NET', 'Cloudflare Inc.', 'NYSE', 1),
('DDOG', 'Datadog Inc.', 'NASDAQ', 1),
('TEAM', 'Atlassian Corporation', 'NASDAQ', 1),
('TTWO', 'Take-Two Interactive Software Inc.', 'NASDAQ', 1),
('EA', 'Electronic Arts Inc.', 'NASDAQ', 1),
('ZG', 'Zillow Group Inc.', 'NASDAQ', 1),
('SPLK', 'Splunk Inc.', 'NASDAQ', 1),
('TTD', 'The Trade Desk Inc.', 'NASDAQ', 1),
('RBLX', 'Roblox Corporation', 'NYSE', 1),
('SQ', 'Block Inc.', 'NYSE', 1),
('HOOD', 'Robinhood Markets Inc.', 'NASDAQ', 1),
('COIN', 'Coinbase Global Inc.', 'NASDAQ', 1),
('SOFI', 'SoFi Technologies Inc.', 'NASDAQ', 1),
('AFRM', 'Affirm Holdings Inc.', 'NASDAQ', 1),
('UPST', 'Upstart Holdings Inc.', 'NASDAQ', 1),
('LCID', 'Lucid Group Inc.', 'NASDAQ', 1),
('RIVN', 'Rivian Automotive Inc.', 'NASDAQ', 1),
('NIO', 'NIO Inc.', 'NYSE', 1),
('XPEV', 'XPeng Inc.', 'NYSE', 1),
('LI', 'Li Auto Inc.', 'NASDAQ', 1),
('BABA', 'Alibaba Group Holding Limited', 'NYSE', 1),
('JD', 'JD.com Inc.', 'NASDAQ', 1),
('PDD', 'PDD Holdings Inc.', 'NASDAQ', 1),
('BIDU', 'Baidu Inc.', 'NASDAQ', 1),
('TME', 'Tencent Music Entertainment Group', 'NYSE', 1),
('NTES', 'NetEase Inc.', 'NASDAQ', 1),
('WB', 'Weibo Corporation', 'NASDAQ', 1),
('BILI', 'Bilibili Inc.', 'NASDAQ', 1),
('VIPS', 'Vipshop Holdings Limited', 'NYSE', 1),
('WB', 'Weibo Corporation', 'NASDAQ', 1),
('YMM', 'Full Truck Alliance Co. Ltd.', 'NYSE', 1),
('GS', 'The Goldman Sachs Group Inc.', 'NYSE', 1),
('MS', 'Morgan Stanley', 'NYSE', 1),
('BK', 'The Bank of New York Mellon Corporation', 'NYSE', 1),
('STT', 'State Street Corporation', 'NYSE', 1),
('COF', 'Capital One Financial Corporation', 'NYSE', 1),
('SYF', 'Synchrony Financial', 'NYSE', 1),
('ALLY', 'Ally Financial Inc.', 'NYSE', 1),
('CFG', 'Citizens Financial Group Inc.', 'NYSE', 1),
('MTB', 'M&T Bank Corporation', 'NYSE', 1),
('ZION', 'Zions Bancorporation N.A.', 'NASDAQ', 1),
('HBAN', 'Huntington Bancshares Incorporated', 'NASDAQ', 1),
('RF', 'Regions Financial Corporation', 'NYSE', 1),
('FITB', 'Fifth Third Bancorp', 'NASDAQ', 1),
('KEY', 'KeyCorp', 'NYSE', 1),
('TFC', 'Truist Financial Corporation', 'NYSE', 1),
('PNC', 'The PNC Financial Services Group Inc.', 'NYSE', 1),
('USB', 'U.S. Bancorp', 'NYSE', 1),
('WFC', 'Wells Fargo & Company', 'NYSE', 1),
('T', 'AT&T Inc.', 'NYSE', 1),
('TMUS', 'T-Mobile US Inc.', 'NASDAQ', 1),
('LUMN', 'Lumen Technologies Inc.', 'NYSE', 1),
('F', 'Ford Motor Company', 'NYSE', 1),
('GM', 'General Motors Company', 'NYSE', 1),
('STLA', 'Stellantis N.V.', 'NYSE', 1),
('RACE', 'Ferrari N.V.', 'NYSE', 1),
('HMC', 'Honda Motor Co. Ltd.', 'NYSE', 1),
('TM', 'Toyota Motor Corporation', 'NYSE', 1),
('NSANY', 'Nissan Motor Co. Ltd.', 'OTC', 1),
('FCAU', 'Stellantis N.V.', 'NYSE', 1),
('X', 'United States Steel Corporation', 'NYSE', 1),
('NUE', 'Nucor Corporation', 'NYSE', 1),
('STLD', 'Steel Dynamics Inc.', 'NASDAQ', 1),
('CLF', 'Cleveland-Cliffs Inc.', 'NYSE', 1),
('RS', 'Reliance Steel & Aluminum Co.', 'NYSE', 1),
('CMC', 'Commercial Metals Company', 'NYSE', 1),
('ZIM', 'ZIM Integrated Shipping Services Ltd.', 'NYSE', 1),
('GOGL', 'Golden Ocean Group Limited', 'NASDAQ', 1),
('NMM', 'Navios Maritime Partners L.P.', 'NYSE', 1),
('EGLE', 'Eagle Bulk Shipping Inc.', 'NASDAQ', 1),
('SBLK', 'Star Bulk Carriers Corp.', 'NASDAQ', 1),
('GNK', 'Genco Shipping & Trading Limited', 'NYSE', 1),
('INTC', 'Intel Corporation', 'NASDAQ', 1),
('MU', 'Micron Technology Inc.', 'NASDAQ', 1),
('WDC', 'Western Digital Corporation', 'NASDAQ', 1),
('STX', 'Seagate Technology Holdings plc', 'NASDAQ', 1),
('LRCX', 'Lam Research Corporation', 'NASDAQ', 1),
('NXPI', 'NXP Semiconductors N.V.', 'NASDAQ', 1),
('NXPI', 'NXP Semiconductors N.V.', 'NASDAQ', 1),
('WOLF', 'Wolfspeed Inc.', 'NYSE', 1),
('ON', 'ON Semiconductor Corporation', 'NASDAQ', 1),
('CRUS', 'Cirrus Logic Inc.', 'NASDAQ', 1),
('MRVL', 'Marvell Technology Inc.', 'NASDAQ', 1),
('RMBS', 'Rambus Inc.', 'NASDAQ', 1),
('ALGM', 'Allegro MicroSystems Inc.', 'NASDAQ', 1),
('SLAB', 'Silicon Laboratories Inc.', 'NASDAQ', 1),
('IMOS', 'ChipMOS TECHNOLOGIES INC.', 'NASDAQ', 1),
('OLED', 'Universal Display Corporation', 'NASDAQ', 1),
('OLED', 'Universal Display Corporation', 'NASDAQ', 1),
('AAPL', 'Apple Inc.', 'NASDAQ', 1),
('MSFT', 'Microsoft Corporation', 'NASDAQ', 1),
('GOOGL', 'Alphabet Inc.', 'NASDAQ', 1),
('AMZN', 'Amazon.com Inc.', 'NASDAQ', 1),
('NVDA', 'NVIDIA Corporation', 'NASDAQ', 1),
('META', 'Meta Platforms Inc.', 'NASDAQ', 1),
('TSLA', 'Tesla Inc.', 'NASDAQ', 1),
('BRK.B', 'Berkshire Hathaway Inc.', 'NYSE', 1),
('V', 'Visa Inc.', 'NYSE', 1),
('JNJ', 'Johnson & Johnson', 'NYSE', 1),
('WMT', 'Walmart Inc.', 'NYSE', 1),
('JPM', 'JPMorgan Chase & Co.', 'NYSE', 1),
('MA', 'Mastercard Incorporated', 'NYSE', 1),
('PG', 'The Procter & Gamble Company', 'NYSE', 1),
('UNH', 'UnitedHealth Group Incorporated', 'NYSE', 1),
('HD', 'The Home Depot Inc.', 'NYSE', 1),
('DIS', 'The Walt Disney Company', 'NYSE', 1),
('BAC', 'Bank of America Corp.', 'NYSE', 1),
('ADBE', 'Adobe Inc.', 'NASDAQ', 1),
('NFLX', 'Netflix Inc.', 'NASDAQ', 1),
('PYPL', 'PayPal Holdings Inc.', 'NASDAQ', 1),
('CMCSA', 'Comcast Corporation', 'NASDAQ', 1),
('XOM', 'Exxon Mobil Corporation', 'NYSE', 1),
('VZ', 'Verizon Communications Inc.', 'NYSE', 1),
('CSCO', 'Cisco Systems Inc.', 'NASDAQ', 1),
('PFE', 'Pfizer Inc.', 'NYSE', 1),
('CVX', 'Chevron Corporation', 'NYSE', 1),
('ABT', 'Abbott Laboratories', 'NYSE', 1),
('KO', 'The Coca-Cola Company', 'NYSE', 1),
('AVGO', 'Broadcom Inc.', 'NASDAQ', 1),
('COST', 'Costco Wholesale Corporation', 'NASDAQ', 1),
('MRK', 'Merck & Co. Inc.', 'NYSE', 1),
('PEP', 'PepsiCo Inc.', 'NASDAQ', 1),
('TMO', 'Thermo Fisher Scientific Inc.', 'NYSE', 1),
('ACN', 'Accenture plc', 'NYSE', 1),
('ABBV', 'AbbVie Inc.', 'NYSE', 1),
('TXN', 'Texas Instruments Incorporated', 'NASDAQ', 1),
('NKE', 'Nike Inc.', 'NYSE', 1),
('MDT', 'Medtronic plc', 'NYSE', 1),
('HON', 'Honeywell International Inc.', 'NASDAQ', 1),
('QCOM', 'QUALCOMM Incorporated', 'NASDAQ', 1),
('PM', 'Philip Morris International Inc.', 'NYSE', 1),
('LIN', 'Linde plc', 'NYSE', 1),
('RTX', 'Raytheon Technologies Corporation', 'NYSE', 1),
('LOW', 'Lowe''s Companies Inc.', 'NYSE', 1),
('AMGN', 'Amgen Inc.', 'NASDAQ', 1),
('BMY', 'Bristol-Myers Squibb Company', 'NYSE', 1),
('UPS', 'United Parcel Service Inc.', 'NYSE', 1),
('DE', 'Deere & Company', 'NYSE', 1),
('SBUX', 'Starbucks Corporation', 'NASDAQ', 1),
('INTU', 'Intuit Inc.', 'NASDAQ', 1),
('CAT', 'Caterpillar Inc.', 'NYSE', 1),
('AMAT', 'Applied Materials Inc.', 'NASDAQ', 1),
('ISRG', 'Intuitive Surgical Inc.', 'NASDAQ', 1),
('ADP', 'Automatic Data Processing Inc.', 'NASDAQ', 1),
('BKNG', 'Booking Holdings Inc.', 'NASDAQ', 1),
('CI', 'Cigna Corporation', 'NYSE', 1),
('GILD', 'Gilead Sciences Inc.', 'NASDAQ', 1),
('ELV', 'Elevance Health Inc.', 'NYSE', 1),
('SCHW', 'The Charles Schwab Corporation', 'NYSE', 1),
('AXP', 'American Express Company', 'NYSE', 1),
('GE', 'General Electric Company', 'NYSE', 1),
('LMT', 'Lockheed Martin Corporation', 'NYSE', 1),
('BLK', 'BlackRock Inc.', 'NYSE', 1),
('C', 'Citigroup Inc.', 'NYSE', 1),
('REGN', 'Regeneron Pharmaceuticals Inc.', 'NASDAQ', 1),
('AMD', 'Advanced Micro Devices Inc.', 'NASDAQ', 1),
('DHR', 'Danaher Corporation', 'NYSE', 1),
('NOW', 'ServiceNow Inc.', 'NYSE', 1),
('ADI', 'Analog Devices Inc.', 'NASDAQ', 1),
('PLD', 'Prologis Inc.', 'NYSE', 1),
('TJX', 'The TJX Companies Inc.', 'NYSE', 1),
('CDNS', 'Cadence Design Systems Inc.', 'NASDAQ', 1),
('SNPS', 'Synopsys Inc.', 'NASDAQ', 1),
('AON', 'Aon plc', 'NYSE', 1),
('ZTS', 'Zoetis Inc.', 'NYSE', 1),
('EQIX', 'Equinix Inc.', 'NASDAQ', 1),
('FI', 'Fiserv Inc.', 'NASDAQ', 1),
('CME', 'CME Group Inc.', 'NASDAQ', 1),
('APH', 'Amphenol Corporation', 'NYSE', 1),
('KLAC', 'KLA Corporation', 'NASDAQ', 1),
('FAST', 'Fastenal Company', 'NASDAQ', 1),
('MCHP', 'Microchip Technology Incorporated', 'NASDAQ', 1),
('PANW', 'Palo Alto Networks Inc.', 'NASDAQ', 1),
('CDW', 'CDW Corporation', 'NASDAQ', 1),
('FTNT', 'Fortinet Inc.', 'NASDAQ', 1),
('PAYX', 'Paychex Inc.', 'NASDAQ', 1),
('TGT', 'Target Corporation', 'NYSE', 1),
('VRTX', 'Vertex Pharmaceuticals Incorporated', 'NASDAQ', 1),
('ALGN', 'Align Technology Inc.', 'NASDAQ', 1),
('IDXX', 'IDEXX Laboratories Inc.', 'NASDAQ', 1),
('DXCM', 'Dexcom Inc.', 'NASDAQ', 1),
('ODFL', 'Old Dominion Freight Line Inc.', 'NASDAQ', 1),
('CHTR', 'Charter Communications Inc.', 'NASDAQ', 1),
('ANSS', 'ANSYS Inc.', 'NASDAQ', 1),
('MELI', 'MercadoLibre Inc.', 'NASDAQ', 1),
('BKR', 'Baker Hughes Company', 'NASDAQ', 1),
('ETN', 'Eaton Corporation plc', 'NYSE', 1),
('CMI', 'Cummins Inc.', 'NYSE', 1),
('APH', 'Amphenol Corporation', 'NYSE', 1),
('FDX', 'FedEx Corporation', 'NYSE', 1),
('PCAR', 'PACCAR Inc', 'NASDAQ', 1),
('NDAQ', 'Nasdaq Inc.', 'NASDAQ', 1),
('MTCH', 'Match Group Inc.', 'NASDAQ', 1),
('ON', 'ON Semiconductor Corporation', 'NASDAQ', 1),
('MPWR', 'Monolithic Power Systems Inc.', 'NASDAQ', 1),
('SWAV', 'Shockwave Medical Inc.', 'NASDAQ', 1),
('ZS', 'Zscaler Inc.', 'NASDAQ', 1),
('DOCN', 'DigitalOcean Holdings Inc.', 'NYSE', 1),
('CRWD', 'CrowdStrike Holdings Inc.', 'NASDAQ', 1),
('NET', 'Cloudflare Inc.', 'NYSE', 1),
('DDOG', 'Datadog Inc.', 'NASDAQ', 1),
('TEAM', 'Atlassian Corporation', 'NASDAQ', 1),
('TTWO', 'Take-Two Interactive Software Inc.', 'NASDAQ', 1),
('EA', 'Electronic Arts Inc.', 'NASDAQ', 1),
('ZG', 'Zillow Group Inc.', 'NASDAQ', 1),
('SPLK', 'Splunk Inc.', 'NASDAQ', 1),
('TTD', 'The Trade Desk Inc.', 'NASDAQ', 1),
('RBLX', 'Roblox Corporation', 'NYSE', 1),
('SQ', 'Block Inc.', 'NYSE', 1),
('HOOD', 'Robinhood Markets Inc.', 'NASDAQ', 1),
('COIN', 'Coinbase Global Inc.', 'NASDAQ', 1),
('SOFI', 'SoFi Technologies Inc.', 'NASDAQ', 1),
('AFRM', 'Affirm Holdings Inc.', 'NASDAQ', 1),
('UPST', 'Upstart Holdings Inc.', 'NASDAQ', 1),
('LCID', 'Lucid Group Inc.', 'NASDAQ', 1),
('RIVN', 'Rivian Automotive Inc.', 'NASDAQ', 1),
('NIO', 'NIO Inc.', 'NYSE', 1),
('XPEV', 'XPeng Inc.', 'NYSE', 1),
('LI', 'Li Auto Inc.', 'NASDAQ', 1),
('BABA', 'Alibaba Group Holding Limited', 'NYSE', 1),
('JD', 'JD.com Inc.', 'NASDAQ', 1),
('PDD', 'PDD Holdings Inc.', 'NASDAQ', 1),
('BIDU', 'Baidu Inc.', 'NASDAQ', 1),
('TME', 'Tencent Music Entertainment Group', 'NYSE', 1),
('NTES', 'NetEase Inc.', 'NASDAQ', 1),
('WB', 'Weibo Corporation', 'NASDAQ', 1),
('BILI', 'Bilibili Inc.', 'NASDAQ', 1),
('VIPS', 'Vipshop Holdings Limited', 'NYSE', 1),
('WB', 'Weibo Corporation', 'NASDAQ', 1),
('YMM', 'Full Truck Alliance Co. Ltd.', 'NYSE', 1),
('GS', 'The Goldman Sachs Group Inc.', 'NYSE', 1),
('MS', 'Morgan Stanley', 'NYSE', 1),
('BK', 'The Bank of New York Mellon Corporation', 'NYSE', 1),
('STT', 'State Street Corporation', 'NYSE', 1),
('COF', 'Capital One Financial Corporation', 'NYSE', 1),
('SYF', 'Synchrony Financial', 'NYSE', 1),
('ALLY', 'Ally Financial Inc.', 'NYSE', 1),
('CFG', 'Citizens Financial Group Inc.', 'NYSE', 1),
('MTB', 'M&T Bank Corporation', 'NYSE', 1),
('ZION', 'Zions Bancorporation N.A.', 'NASDAQ', 1),
('HBAN', 'Huntington Bancshares Incorporated', 'NASDAQ', 1),
('RF', 'Regions Financial Corporation', 'NYSE', 1),
('FITB', 'Fifth Third Bancorp', 'NASDAQ', 1),
('KEY', 'KeyCorp', 'NYSE', 1),
('TFC', 'Truist Financial Corporation', 'NYSE', 1),
('PNC', 'The PNC Financial Services Group Inc.', 'NYSE', 1),
('USB', 'U.S. Bancorp', 'NYSE', 1),
('WFC', 'Wells Fargo & Company', 'NYSE', 1),
('T', 'AT&T Inc.', 'NYSE', 1),
('TMUS', 'T-Mobile US Inc.', 'NASDAQ', 1),
('LUMN', 'Lumen Technologies Inc.', 'NYSE', 1),
('F', 'Ford Motor Company', 'NYSE', 1),
('GM', 'General Motors Company', 'NYSE', 1),
('STLA', 'Stellantis N.V.', 'NYSE', 1),
('RACE', 'Ferrari N.V.', 'NYSE', 1),
('HMC', 'Honda Motor Co. Ltd.', 'NYSE', 1),
('TM', 'Toyota Motor Corporation', 'NYSE', 1),
('NSANY', 'Nissan Motor Co. Ltd.', 'OTC', 1),
('FCAU', 'Stellantis N.V.', 'NYSE', 1),
('X', 'United States Steel Corporation', 'NYSE', 1),
('NUE', 'Nucor Corporation', 'NYSE', 1),
('STLD', 'Steel Dynamics Inc.', 'NASDAQ', 1),
('CLF', 'Cleveland-Cliffs Inc.', 'NYSE', 1),
('RS', 'Reliance Steel & Aluminum Co.', 'NYSE', 1),
('CMC', 'Commercial Metals Company', 'NYSE', 1),
('ZIM', 'ZIM Integrated Shipping Services Ltd.', 'NYSE', 1),
('GOGL', 'Golden Ocean Group Limited', 'NASDAQ', 1),
('NMM', 'Navios Maritime Partners L.P.', 'NYSE', 1),
('EGLE', 'Eagle Bulk Shipping Inc.', 'NASDAQ', 1),
('SBLK', 'Star Bulk Carriers Corp.', 'NASDAQ', 1),
('GNK', 'Genco Shipping & Trading Limited', 'NYSE', 1),
('INTC', 'Intel Corporation', 'NASDAQ', 1),
('MU', 'Micron Technology Inc.', 'NASDAQ', 1),
('WDC', 'Western Digital Corporation', 'NASDAQ', 1),
('STX', 'Seagate Technology Holdings plc', 'NASDAQ', 1),
('LRCX', 'Lam Research Corporation', 'NASDAQ', 1),
('NXPI', 'NXP Semiconductors N.V.', 'NASDAQ', 1),
('NXPI', 'NXP Semiconductors N.V.', 'NASDAQ', 1),
('WOLF', 'Wolfspeed Inc.', 'NYSE', 1),
('ON', 'ON Semiconductor Corporation', 'NASDAQ', 1),
('CRUS', 'Cirrus Logic Inc.', 'NASDAQ', 1),
('MRVL', 'Marvell Technology Inc.', 'NASDAQ', 1),
('RMBS', 'Rambus Inc.', 'NASDAQ', 1),
('ALGM', 'Allegro MicroSystems Inc.', 'NASDAQ', 1),
('SLAB', 'Silicon Laboratories Inc.', 'NASDAQ', 1),
('IMOS', 'ChipMOS TECHNOLOGIES INC.', 'NASDAQ', 1),
('OLED', 'Universal Display Corporation', 'NASDAQ', 1),
('OLED', 'Universal Display Corporation', 'NASDAQ', 1),
('MO', 'Altria Group Inc.', 'NYSE', 1),
('TAP', 'Molson Coors Beverage Company', 'NYSE', 1),
('STZ', 'Constellation Brands Inc.', 'NYSE', 1),
('BF.B', 'Brown-Forman Corporation', 'NYSE', 1),
('SAM', 'The Boston Beer Company Inc.', 'NYSE', 1),
('MGPI', 'MGP Ingredients Inc.', 'NASDAQ', 1),
('FIZZ', 'National Beverage Corp.', 'NASDAQ', 1),
('LIFE', 'aTyr Pharma Inc.', 'NASDAQ', 1),
('DEO', 'Diageo plc', 'NYSE', 1),
('HLF', 'Herbalife Nutrition Ltd.', 'NYSE', 1),
('USFD', 'US Foods Holding Corp.', 'NYSE', 1),
('SYY', 'Sysco Corporation', 'NYSE', 1),
('PFGC', 'Performance Food Group Company', 'NYSE', 1),
('USFD', 'US Foods Holding Corp.', 'NYSE', 1),
('CTRA', 'Coterra Energy Inc.', 'NYSE', 1),
('EOG', 'EOG Resources Inc.', 'NYSE', 1),
('COP', 'ConocoPhillips', 'NYSE', 1),
('MPC', 'Marathon Petroleum Corporation', 'NYSE', 1),
('VLO', 'Valero Energy Corporation', 'NYSE', 1),
('PSX', 'Phillips 66', 'NYSE', 1),
('HES', 'Hess Corporation', 'NYSE', 1),
('DVN', 'Devon Energy Corporation', 'NYSE', 1),
('FANG', 'Diamondback Energy Inc.', 'NASDAQ', 1),
('MRO', 'Marathon Oil Corporation', 'NYSE', 1),
('OXY', 'Occidental Petroleum Corporation', 'NYSE', 1),
('SLB', 'Schlumberger Limited', 'NYSE', 1),
('HAL', 'Halliburton Company', 'NYSE', 1),
('BKR', 'Baker Hughes Company', 'NASDAQ', 1),
('NOV', 'National Oilwell Varco Inc.', 'NYSE', 1),
('FTI', 'TechnipFMC plc', 'NYSE', 1),
('WFRD', 'Weatherford International plc', 'NASDAQ', 1),
('CHX', 'ChampionX Corporation', 'NASDAQ', 1),
('RES', 'RPC Inc.', 'NYSE', 1),
('HP', 'Helmerich & Payne Inc.', 'NYSE', 1),
('PTEN', 'Patterson-UTI Energy Inc.', 'NASDAQ', 1),
('NBR', 'Nabors Industries Ltd.', 'NYSE', 1),
('LBRT', 'Liberty Energy Inc.', 'NYSE', 1),
('PUMP', 'ProPetro Holding Corp.', 'NYSE', 1),
('WTTR', 'Select Energy Services Inc.', 'NYSE', 1),
('CLB', 'Core Laboratories N.V.', 'NYSE', 1),
('OII', 'Oceaneering International Inc.', 'NYSE', 1),
('DO', 'Diamond Offshore Drilling Inc.', 'NYSE', 1),
('RIG', 'Transocean Ltd.', 'NYSE', 1),
('VAL', 'Valaris Limited', 'NYSE', 1),
('SDRL', 'Seadrill Limited', 'NYSE', 1),
('BORR', 'Borr Drilling Limited', 'NYSE', 1),
('NAT', 'Nordic American Tankers Limited', 'NYSE', 1),
('INSW', 'International Seaways Inc.', 'NYSE', 1),
('TNK', 'Teekay Tankers Ltd.', 'NYSE', 1),
('DHT', 'DHT Holdings Inc.', 'NYSE', 1),
('FRO', 'Frontline plc', 'NYSE', 1),
('TGP', 'Teekay LNG Partners L.P.', 'NYSE', 1),
('GSL', 'Global Ship Lease Inc.', 'NYSE', 1),
('DAC', 'Danaos Corporation', 'NYSE', 1),
('CPLP', 'Capital Product Partners L.P.', 'NASDAQ', 1),
('GNRT', 'Gener8 Maritime Inc.', 'NYSE', 1),
('DLNG', 'Dynagas LNG Partners LP', 'NYSE', 1),
('GLOP', 'GasLog Partners LP', 'NYSE', 1),
('TOPS', 'TOP Ships Inc.', 'NASDAQ', 1),
('SHIP', 'Seanergy Maritime Holdings Corp.', 'NASDAQ', 1),
('GLBS', 'Globus Maritime Limited', 'NASDAQ', 1),
('IMPP', 'Imperial Petroleum Inc.', 'NASDAQ', 1),
('OP', 'OceanPal Inc.', 'NASDAQ', 1),
('USAC', 'USA Compression Partners LP', 'NYSE', 1),
('CEQP', 'Crestwood Equity Partners LP', 'NYSE', 1),
('PBF', 'PBF Energy Inc.', 'NYSE', 1),
('CIVI', 'Civitas Resources Inc.', 'NYSE', 1),
('MUR', 'Murphy Oil Corporation', 'NYSE', 1),
('MTDR', 'Matador Resources Company', 'NYSE', 1),
('MGY', 'Magnolia Oil & Gas Corporation', 'NYSE', 1),
('SWN', 'Southwestern Energy Company', 'NYSE', 1),
('AR', 'Antero Resources Corporation', 'NYSE', 1),
('RRC', 'Range Resources Corporation', 'NYSE', 1),
('CNX', 'CNX Resources Corporation', 'NYSE', 1),
('BRY', 'Berry Corporation', 'NASDAQ', 1),
('WTI', 'W&T Offshore Inc.', 'NYSE', 1),
('REI', 'Ring Energy Inc.', 'NYSE', 1),
('VTLE', 'Vital Energy Inc.', 'NYSE', 1),
('NEXT', 'NextDecade Corporation', 'NASDAQ', 1),
('LNG', 'Cheniere Energy Inc.', 'NYSE', 1),
('TGS', 'Transportadora de Gas del Sur S.A.', 'NYSE', 1),
('KMI', 'Kinder Morgan Inc.', 'NYSE', 1),
('OKE', 'ONEOK Inc.', 'NYSE', 1),
('WMB', 'The Williams Companies Inc.', 'NYSE', 1),
('ENB', 'Enbridge Inc.', 'NYSE', 1),
('TRP', 'TC Energy Corporation', 'NYSE', 1),
('EPD', 'Enterprise Products Partners L.P.', 'NYSE', 1),
('ET', 'Energy Transfer LP', 'NYSE', 1),
('MPLX', 'MPLX LP', 'NYSE', 1),
('PAA', 'Plains All American Pipeline L.P.', 'NASDAQ', 1),
('PAGP', 'Plains GP Holdings L.P.', 'NASDAQ', 1),
('DCP', 'DCP Midstream LP', 'NYSE', 1),
('HESM', 'Hess Midstream Partners LP', 'NYSE', 1),
('GEL', 'Genesis Energy L.P.', 'NYSE', 1),
('NGLS', 'Targa Resources Partners LP', 'NYSE', 1),
('WLKP', 'Westlake Chemical Partners LP', 'NYSE', 1),
('USAC', 'USA Compression Partners LP', 'NYSE', 1),
('CTRA', 'Coterra Energy Inc.', 'NYSE', 1),
('CTRA', 'Coterra Energy Inc.', 'NYSE', 1),
('PBA', 'Pembina Pipeline Corporation', 'NYSE', 1),
('CNQ', 'Canadian Natural Resources Limited', 'NYSE', 1),
('SU', 'Suncor Energy Inc.', 'NYSE', 1),
('IMO', 'Imperial Oil Limited', 'NYSE', 1),
('CVE', 'Cenovus Energy Inc.', 'NYSE', 1),
('MEG', 'MEG Energy Corp.', 'OTC', 1),
('HSE', 'Husky Energy Inc.', 'NYSE', 1),
('TOU', 'Tourmaline Oil Corp.', 'OTC', 1),
('ARX', 'ARC Resources Ltd.', 'OTC', 1),
('CPG', 'Crescent Point Energy Corp.', 'NYSE', 1),
('TVE', 'Tamarack Valley Energy Ltd.', 'OTC', 1),
('WCP', 'Whitecap Resources Inc.', 'OTC', 1),
('PR', 'Permian Resources Corporation', 'NYSE', 1),
('MTCH', 'Match Group Inc.', 'NASDAQ', 1),
('ORLY', 'O''Reilly Automotive Inc.', 'NASDAQ', 1),
('AZO', 'AutoZone Inc.', 'NYSE', 1),
('KMX', 'CarMax Inc.', 'NYSE', 1),
('AN', 'AutoNation Inc.', 'NYSE', 1),
('PAG', 'Penske Automotive Group Inc.', 'NYSE', 1),
('LAD', 'Lithia Motors Inc.', 'NYSE', 1),
('ABG', 'Asbury Automotive Group Inc.', 'NYSE', 1),
('SAH', 'Sonic Automotive Inc.', 'NYSE', 1),
('GP', 'Green Plains Inc.', 'NASDAQ', 1),
('REVG', 'REV Group Inc.', 'NYSE', 1),
('TII', 'Titan International Inc.', 'NYSE', 1),
('WNC', 'Wabash National Corporation', 'NYSE', 1),
('SHYF', 'The Shyft Group Inc.', 'NASDAQ', 1),
('TEX', 'Terex Corporation', 'NYSE', 1),
('OSK', 'Oshkosh Corporation', 'NYSE', 1),
('ASTE', 'Astec Industries Inc.', 'NASDAQ', 1),
('MTZ', 'MasTec Inc.', 'NYSE', 1),
('ROK', 'Rockwell Automation Inc.', 'NYSE', 1),
('EMR', 'Emerson Electric Co.', 'NYSE', 1),
('DOV', 'Dover Corporation', 'NYSE', 1),
('IR', 'Ingersoll Rand Inc.', 'NYSE', 1),
('ITT', 'ITT Inc.', 'NYSE', 1),
('GGG', 'Graco Inc.', 'NYSE', 1),
('GTLS', 'Chart Industries Inc.', 'NYSE', 1),
('FTV', 'Fortive Corporation', 'NYSE', 1),
('SWK', 'Stanley Black & Decker Inc.', 'NYSE', 1),
('PH', 'Parker-Hannifin Corporation', 'NYSE', 1),
('NDSN', 'Nordson Corporation', 'NASDAQ', 1),
('MIDD', 'The Middleby Corporation', 'NASDAQ', 1),
('RBC', 'RBC Bearings Incorporated', 'NYSE', 1),
('HI', 'Hillenbrand Inc.', 'NYSE', 1),
('FLS', 'Flowserve Corporation', 'NYSE', 1),
('AME', 'AMETEK Inc.', 'NYSE', 1),
('GNRC', 'Generac Holdings Inc.', 'NYSE', 1),
('AOS', 'A. O. Smith Corporation', 'NYSE', 1),
('WWD', 'Woodward Inc.', 'NASDAQ', 1),
('FIX', 'Comfort Systems USA Inc.', 'NYSE', 1),
('AZEK', 'The AZEK Company Inc.', 'NYSE', 1),
('APOG', 'Apogee Enterprises Inc.', 'NASDAQ', 1),
('TREX', 'Trex Company Inc.', 'NYSE', 1),
('LII', 'Lennox International Inc.', 'NYSE', 1),
('WSO', 'Watsco Inc.', 'NYSE', 1),
('CARR', 'Carrier Global Corporation', 'NYSE', 1),
('JCI', 'Johnson Controls International plc', 'NYSE', 1),
('TT', 'Trane Technologies plc', 'NYSE', 1),
('FBHS', 'Fortune Brands Home & Security Inc.', 'NYSE', 1),
('MAS', 'Masco Corporation', 'NYSE', 1),
('BECN', 'Beacon Roofing Supply Inc.', 'NASDAQ', 1),
('BMCH', 'BMC Stock Holdings Inc.', 'NASDAQ', 1),
('BLDR', 'Builders FirstSource Inc.', 'NYSE', 1),
('FND', 'Floor & Decor Holdings Inc.', 'NYSE', 1),
('WHD', 'Cactus Inc.', 'NYSE', 1),
('HBP', 'Huttig Building Products Inc.', 'NASDAQ', 1),
('STRL', 'Sterling Infrastructure Inc.', 'NASDAQ', 1),
('GVA', 'Granite Construction Incorporated', 'NYSE', 1),
('ACM', 'AECOM', 'NYSE', 1),
('FIX', 'Comfort Systems USA Inc.', 'NYSE', 1),
('EME', 'EMCOR Group Inc.', 'NYSE', 1),
('PRIM', 'Primoris Services Corporation', 'NASDAQ', 1),
('ROAD', 'Construction Partners Inc.', 'NASDAQ', 1),
('TISI', 'Team Inc.', 'NYSE', 1),
('TNK', 'Teekay Tankers Ltd.', 'NYSE', 1),
('PRIM', 'Primoris Services Corporation', 'NASDAQ', 1),
('ROAD', 'Construction Partners Inc.', 'NASDAQ', 1),
('FCX', 'Freeport-McMoRan Inc.', 'NYSE', 1),
('NEM', 'Newmont Corporation', 'NYSE', 1),
('GOLD', 'Barrick Gold Corporation', 'NYSE', 1),
('AEM', 'Agnico Eagle Mines Limited', 'NYSE', 1),
('FNV', 'Franco-Nevada Corporation', 'NYSE', 1),
('WPM', 'Wheaton Precious Metals Corp.', 'NYSE', 1),
('RGLD', 'Royal Gold Inc.', 'NASDAQ', 1),
('AG', 'First Majestic Silver Corp.', 'NYSE', 1),
('HL', 'Hecla Mining Company', 'NYSE', 1),
('CDE', 'Coeur Mining Inc.', 'NYSE', 1),
('PAAS', 'Pan American Silver Corp.', 'NASDAQ', 1),
('EXK', 'Endeavour Silver Corp.', 'NYSE', 1),
('MAG', 'MAG Silver Corp.', 'NYSE', 1),
('SSRM', 'SSR Mining Inc.', 'NASDAQ', 1),
('SAND', 'Sandstorm Gold Ltd.', 'NYSE', 1),
('OR', 'Osisko Gold Royalties Ltd', 'NYSE', 1),
('NGD', 'New Gold Inc.', 'NYSE', 1),
('KGC', 'Kinross Gold Corporation', 'NYSE', 1),
('AUY', 'Yamana Gold Inc.', 'NYSE', 1),
('BTG', 'B2Gold Corp.', 'NYSE', 1),
('EGO', 'Eldorado Gold Corporation', 'NYSE', 1),
('IAG', 'IAMGOLD Corporation', 'NYSE', 1),
('HMY', 'Harmony Gold Mining Company Limited', 'NYSE', 1),
('GFI', 'Gold Fields Limited', 'NYSE', 1),
('SBSW', 'Sibanye Stillwater Limited', 'NYSE', 1),
('AU', 'AngloGold Ashanti Limited', 'NYSE', 1),
('EGO', 'Eldorado Gold Corporation', 'NYSE', 1),
('AEM', 'Agnico Eagle Mines Limited', 'NYSE', 1),
('KGC', 'Kinross Gold Corporation', 'NYSE', 1),
('IAG', 'IAMGOLD Corporation', 'NYSE', 1),
('NGD', 'New Gold Inc.', 'NYSE', 1),
('OR', 'Osisko Gold Royalties Ltd', 'NYSE', 1),
('PAAS', 'Pan American Silver Corp.', 'NASDAQ', 1),
('CDE', 'Coeur Mining Inc.', 'NYSE', 1),
('HL', 'Hecla Mining Company', 'NYSE', 1),
('AG', 'First Majestic Silver Corp.', 'NYSE', 1),
('RGLD', 'Royal Gold Inc.', 'NASDAQ', 1),
('WPM', 'Wheaton Precious Metals Corp.', 'NYSE', 1),
('FNV', 'Franco-Nevada Corporation', 'NYSE', 1),
('AEM', 'Agnico Eagle Mines Limited', 'NYSE', 1),
('GOLD', 'Barrick Gold Corporation', 'NYSE', 1),
('NEM', 'Newmont Corporation', 'NYSE', 1),
('FCX', 'Freeport-McMoRan Inc.', 'NYSE', 1),
('SCCO', 'Southern Copper Corporation', 'NYSE', 1),
('TECK', 'Teck Resources Limited', 'NYSE', 1),
('VALE', 'Vale S.A.', 'NYSE', 1),
('RIO', 'Rio Tinto Group', 'NYSE', 1),
('BHP', 'BHP Group Limited', 'NYSE', 1),
('VALE', 'Vale S.A.', 'NYSE', 1),
('RIO', 'Rio Tinto Group', 'NYSE', 1),
('BHP', 'BHP Group Limited', 'NYSE', 1),
('SCCO', 'Southern Copper Corporation', 'NYSE', 1),
('TECK', 'Teck Resources Limited', 'NYSE', 1),
('FCX', 'Freeport-McMoRan Inc.', 'NYSE', 1),
('NEM', 'Newmont Corporation', 'NYSE', 1),
('GOLD', 'Barrick Gold Corporation', 'NYSE', 1),
('AEM', 'Agnico Eagle Mines Limited', 'NYSE', 1),
('FNV', 'Franco-Nevada Corporation', 'NYSE', 1),
('WPM', 'Wheaton Precious Metals Corp.', 'NYSE', 1),
('RGLD', 'Royal Gold Inc.', 'NASDAQ', 1),
('AG', 'First Majestic Silver Corp.', 'NYSE', 1),
('HL', 'Hecla Mining Company', 'NYSE', 1),
('CDE', 'Coeur Mining Inc.', 'NYSE', 1),
('PAAS', 'Pan American Silver Corp.', 'NASDAQ', 1),
('OR', 'Osisko Gold Royalties Ltd', 'NYSE', 1),
('NGD', 'New Gold Inc.', 'NYSE', 1),
('IAG', 'IAMGOLD Corporation', 'NYSE', 1),
('KGC', 'Kinross Gold Corporation', 'NYSE', 1),
('AEM', 'Agnico Eagle Mines Limited', 'NYSE', 1),
('EGO', 'Eldorado Gold Corporation', 'NYSE', 1),
('BTG', 'B2Gold Corp.', 'NYSE', 1),
('AUY', 'Yamana Gold Inc.', 'NYSE', 1),
('KGC', 'Kinross Gold Corporation', 'NYSE', 1),
('IAG', 'IAMGOLD Corporation', 'NYSE', 1),
('NGD', 'New Gold Inc.', 'NYSE', 1),
('OR', 'Osisko Gold Royalties Ltd', 'NYSE', 1),
('PAAS', 'Pan American Silver Corp.', 'NASDAQ', 1),
('CDE', 'Coeur Mining Inc.', 'NYSE', 1),
('HL', 'Hecla Mining Company', 'NYSE', 1),
('AG', 'First Majestic Silver Corp.', 'NYSE', 1),
('RGLD', 'Royal Gold Inc.', 'NASDAQ', 1),
('WPM', 'Wheaton Precious Metals Corp.', 'NYSE', 1),
('FNV', 'Franco-Nevada Corporation', 'NYSE', 1),
('AEM', 'Agnico Eagle Mines Limited', 'NYSE', 1),
('GOLD', 'Barrick Gold Corporation', 'NYSE', 1),
('NEM', 'Newmont Corporation', 'NYSE', 1),
('FCX', 'Freeport-McMoRan Inc.', 'NYSE', 1),
('SCCO', 'Southern Copper Corporation', 'NYSE', 1),
('TECK', 'Teck Resources Limited', 'NYSE', 1),
('VALE', 'Vale S.A.', 'NYSE', 1),
('RIO', 'Rio Tinto Group', 'NYSE', 1),
('BHP', 'BHP Group Limited', 'NYSE', 1),
('VALE', 'Vale S.A.', 'NYSE', 1),
('RIO', 'Rio Tinto Group', 'NYSE', 1),
('BHP', 'BHP Group Limited', 'NYSE', 1),
('SCCO', 'Southern Copper Corporation', 'NYSE', 1),
('TECK', 'Teck Resources Limited', 'NYSE', 1),
('FCX', 'Freeport-McMoRan Inc.', 'NYSE', 1),
('NEM', 'Newmont Corporation', 'NYSE', 1),
('GOLD', 'Barrick Gold Corporation', 'NYSE', 1),
('AEM', 'Agnico Eagle Mines Limited', 'NYSE', 1),
('FNV', 'Franco-Nevada Corporation', 'NYSE', 1),
('WPM', 'Wheaton Precious Metals Corp.', 'NYSE', 1),
('RGLD', 'Royal Gold Inc.', 'NASDAQ', 1),
('AG', 'First Majestic Silver Corp.', 'NYSE', 1),
('HL', 'Hecla Mining Company', 'NYSE', 1),
('CDE', 'Coeur Mining Inc.', 'NYSE', 1),
('PAAS', 'Pan American Silver Corp.', 'NASDAQ', 1),
('OR', 'Osisko Gold Royalties Ltd', 'NYSE', 1),
('NGD', 'New Gold Inc.', 'NYSE', 1),
('IAG', 'IAMGOLD Corporation', 'NYSE', 1),
('KGC', 'Kinross Gold Corporation', 'NYSE', 1),
('AEM', 'Agnico Eagle Mines Limited', 'NYSE', 1),
('EGO', 'Eldorado Gold Corporation', 'NYSE', 1),
('BTG', 'B2Gold Corp.', 'NYSE', 1),
('AUY', 'Yamana Gold Inc.', 'NYSE', 1),
('KGC', 'Kinross Gold Corporation', 'NYSE', 1),
('IAG', 'IAMGOLD Corporation', 'NYSE', 1),
('NGD', 'New Gold Inc.', 'NYSE', 1),
('OR', 'Osisko Gold Royalties Ltd', 'NYSE', 1),
('PAAS', 'Pan American Silver Corp.', 'NASDAQ', 1),
('CDE', 'Coeur Mining Inc.', 'NYSE', 1),
('HL', 'Hecla Mining Company', 'NYSE', 1),
('AG', 'First Majestic Silver Corp.', 'NYSE', 1),
('RGLD', 'Royal Gold Inc.', 'NASDAQ', 1),
('WPM', 'Wheaton Precious Metals Corp.', 'NYSE', 1),
('FNV', 'Franco-Nevada Corporation', 'NYSE', 1),
('AEM', 'Agnico Eagle Mines Limited', 'NYSE', 1),
('GOLD', 'Barrick Gold Corporation', 'NYSE', 1),
('NEM', 'Newmont Corporation', 'NYSE', 1),
('FCX', 'Freeport-McMoRan Inc.', 'NYSE', 1),
('SCCO', 'Southern Copper Corporation', 'NYSE', 1),
('TECK', 'Teck Resources Limited', 'NYSE', 1),
('VALE', 'Vale S.A.', 'NYSE', 1),
('RIO', 'Rio Tinto Group', 'NYSE', 1),
('BHP', 'BHP Group Limited', 'NYSE', 1);

